data_ingestion:
  root_directory: artifacts/Data
  local_data_file: artifacts/Data/Data.csv
  train_data_file: artifacts/Data/train.csv
  test_data_file: artifacts/Data/test.csv
  remove_cols: ["gill-spacing" , "stem-root" , "stem-surface" , "veil-type" , "veil-color" , "spore-print-color","has-ring"]
  output_mapping: {"p" : 0 , "e" : 1}
  test_size: 0.25

data_transformation:
  ohe_model_path: artifacts/model/OneHotEncoder.pickle
  preprocess_path: artifacts/model/preprocessor.pkl
  target_col: class
  num_cols:  ['cap_diameter', 'stem_height','stem_width']
  cat_cols: ['cap_shape', 'cap_surface', 'cap_color', 'gill_attachment', 'gill_color', 'stem_color', 'ring_type', 'habitat']
  ohe_cols: ['does-bruise-or-bleed' , 'season']


model_trainer:
  model_saved_path: artifacts/Model/model.pkl
  models: {'LogisticRegression':LogisticRegression(class_weight='balanced', random_state=42 , solver='liblinear'),'RandomForest':RandomForestClassifier(bootstrap= False, max_depth= 20, max_features= "log2", min_samples_leaf= 3, min_samples_split= 6, n_estimators= 60),'XgBoost':XGBClassifier(objective='binary:logistic',eval_metric='logloss'),'DecisionTree':DecisionTreeClassifier(criterion='gini', splitter='best'),'KNN' :KNeighborsClassifier(n_neighbors=5),'NavieBayes' :BernoulliNB(alpha=1.0, binarize=0.0, fit_prior=True, class_prior=None),'SVM' : SVC(C=1.0 , class_weight='balanced')}

